### ISSUE TITLE
Fix Factorial for big numbers

### ISSUE THREAD

**Issue by Srijita-Mandal** [Srijita-Mandal/fix-your-nums#54]
In Factorial calculator, if large numbers are given, the result comes when the page looks very bad and not responsive. 
For `large numbers`, make the result should come `exponentially` and after a certain value it will show `Infinity`.

**Comment by priyanka1551** [comment]
@Srijita-Mandal I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Go for it.

**Comment by Srijita-Mandal** [comment]
@priyanka1551 Is this done? Make your PR by today.

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@deepbeatz You are assigned. Go for it.

**Comment by deepbeatz** [comment]
Thanks ma'am , will get back to you tomorrow itself

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2023-02-18 18 32 52" src="https://user-images.githubusercontent.com/79015311/219867295-3c462f40-ca46-4944-857d-bf307afefc14.png">

<img width="960" alt="Screenshot 2023-02-18 18 33 08" src="https://user-images.githubusercontent.com/79015311/219867300-82acc484-ebf7-417f-8c57-2b3614a97568.png">

<img width="960" alt="Screenshot 2023-02-18 18 33 18" src="https://user-images.githubusercontent.com/79015311/219867302-6bbf4a5a-7b13-483e-a176-d9e691d27f34.png">

<img width="960" alt="Screenshot 2023-02-18 18 33 27" src="https://user-images.githubusercontent.com/79015311/219867303-65ba3279-ce1a-4aa9-8f2e-547aa92d1fc7.png">

<img width="960" alt="Screenshot 2023-02-18 18 33 35" src="https://user-images.githubusercontent.com/79015311/219867305-4ebe8b42-e48c-446e-9418-9374ab948b58.png">

i have made the changes as you can see, i have taken the limit input number as 52 because after 52 the responsiveness starts disturbing, so 52 and above whatever no. we give we will get answer in terms of "e", and above 170 it will show infinity as answer. plz let me know if i can raise a PR now

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2023-02-18 18 39 19" src="https://user-images.githubusercontent.com/79015311/219867552-2f984d3c-aa13-47c7-8e1d-bc7a745adc42.png">
what i have done is highlighted here , plz check @Srijita-Mandal

**Comment by deepbeatz** [comment]
i raised a PR maam @Srijita-Mandal
